# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T12:43:01+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, List, Optional

from pydantic import BaseModel, Field, RootModel, conint, constr


class AccessDeniedException(RootModel[Any]):
    root: Any


class ControlId(
    RootModel[constr(pattern=r'^hrc-[a-z0-9]{12}$', min_length=1, max_length=50)]
):
    root: constr(pattern=r'^hrc-[a-z0-9]{12}$', min_length=1, max_length=50)


class DescribeHomeRegionControlsMaxResults(RootModel[conint(ge=1, le=100)]):
    root: conint(ge=1, le=100)


class DryRun(RootModel[bool]):
    root: bool


class DryRunOperation(RootModel[Any]):
    root: Any


class GetHomeRegionRequest(BaseModel):
    pass


class HomeRegion(
    RootModel[
        constr(pattern=r'^([a-z]+)-([a-z]+)-([0-9]+)$', min_length=1, max_length=50)
    ]
):
    root: constr(pattern=r'^([a-z]+)-([a-z]+)-([0-9]+)$', min_length=1, max_length=50)


class InternalServerError(RootModel[Any]):
    root: Any


class InvalidInputException(RootModel[Any]):
    root: Any


class RequestedTime(RootModel[datetime]):
    root: datetime


class ServiceUnavailableException(RootModel[Any]):
    root: Any


class TargetId(RootModel[constr(pattern=r'^\d{12}$', min_length=12, max_length=12)]):
    root: constr(pattern=r'^\d{12}$', min_length=12, max_length=12)


class TargetType(Enum):
    ACCOUNT = 'ACCOUNT'


class ThrottlingException(RootModel[Any]):
    root: Any


class Token(
    RootModel[
        constr(pattern=r'^[a-zA-Z0-9\/\+\=]{0,2048}$', min_length=0, max_length=2048)
    ]
):
    root: constr(pattern=r'^[a-zA-Z0-9\/\+\=]{0,2048}$', min_length=0, max_length=2048)


class XAmzTarget(Enum):
    AWSMigrationHubMultiAccountService_CreateHomeRegionControl = (
        'AWSMigrationHubMultiAccountService.CreateHomeRegionControl'
    )


class XAmzTarget1(Enum):
    AWSMigrationHubMultiAccountService_DescribeHomeRegionControls = (
        'AWSMigrationHubMultiAccountService.DescribeHomeRegionControls'
    )


class XAmzTarget2(Enum):
    AWSMigrationHubMultiAccountService_GetHomeRegion = (
        'AWSMigrationHubMultiAccountService.GetHomeRegion'
    )


class GetHomeRegionResult(BaseModel):
    HomeRegion_1: Optional[HomeRegion] = Field(None, alias='HomeRegion')


class Target(BaseModel):
    Id: Optional[TargetId] = None
    Type: TargetType


class CreateHomeRegionControlRequest(BaseModel):
    DryRun_1: Optional[DryRun] = Field(None, alias='DryRun')
    HomeRegion_1: HomeRegion = Field(..., alias='HomeRegion')
    Target_1: Target = Field(..., alias='Target')


class DescribeHomeRegionControlsRequest(BaseModel):
    ControlId_1: Optional[ControlId] = Field(None, alias='ControlId')
    HomeRegion_1: Optional[HomeRegion] = Field(None, alias='HomeRegion')
    MaxResults: Optional[DescribeHomeRegionControlsMaxResults] = None
    NextToken: Optional[Token] = None
    Target_1: Optional[Target] = Field(None, alias='Target')


class HomeRegionControl(BaseModel):
    ControlId_1: Optional[ControlId] = Field(None, alias='ControlId')
    HomeRegion_1: Optional[HomeRegion] = Field(None, alias='HomeRegion')
    RequestedTime_1: Optional[RequestedTime] = Field(None, alias='RequestedTime')
    Target_1: Optional[Target] = Field(None, alias='Target')


class HomeRegionControls(RootModel[List[HomeRegionControl]]):
    root: List[HomeRegionControl] = Field(..., max_length=100)


class CreateHomeRegionControlResult(BaseModel):
    HomeRegionControl_1: Optional[HomeRegionControl] = Field(
        None, alias='HomeRegionControl'
    )


class DescribeHomeRegionControlsResult(BaseModel):
    HomeRegionControls_1: Optional[HomeRegionControls] = Field(
        None, alias='HomeRegionControls'
    )
    NextToken: Optional[Token] = None
